# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WP Tips

description: > # this means to ignore newlines until "baseurl:"
  WordPress tips readable in less than 2 minutes!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wptips.co" # the base hostname & protocol for your site
github_username:  thanhluu

# Build settings
markdown: kramdown
